version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: lelo-postgres
    environment:
      POSTGRES_DB: lelo_angola
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: lelo-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

volumes:
  postgres_data: